application: sunnyg-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /unit2/bday.*
  script: bday.app

- url: /unit2/rot13.*
  script: rot13.app

- url: /unit2/signup.*
  script: signup.app

- url: /unit2/welcome.*
  script: signup.app
